version: '3.8'

services:
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=DE Berlin
      - PORT_FORWARD_ONLY=true
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER="private internet access"
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HTTPPROXY=on
    networks:
      - mynetwork
    ports:
      - "8003:8003" # Joal port
      - "2222:22" # ssh port
      - "80:80" # swizzin port
      - "443:443" # https port
  swizzin:
    image: swizzin
    build:
      context: .
      args:
        - TERM=${TERM}
        - SEEDBOX_USER=${SEEDBOX_USER}
        - SEEDBOX_PASS=${SEEDBOX_PASS}
    container_name: debian_ssh_container
    restart: unless-stopped
    privileged: true
    network_mode: service:vpn
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - ./data/downloads:/home/${SEEDBOX_USER}/transmission/downloads
      - ./data/torrents:/home/${SEEDBOX_USER}/transmission/watch
      - ./config:/home/${SEEDBOX_USER}/.config
      - ./config/Jackett/ygg-api.yml:/home/${SEEDBOX_USER}/Jackett/Definitions/ygg-api.yml
  joal:
    image: anthonyraymond/joal
    container_name: joal
    restart: unless-stopped
    volumes:
      - ./joal:/data
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=8003", "--joal.ui.path.prefix=${JOAL_PREFIX}", "--joal.ui.secret-token=${JOAL_SECRET}"]
    network_mode: service:vpn
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    ports:
      - "8888:8888" # resilio ui port
      - "55555:55555" # resilio port
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/downloads:/sync/downloads
      - ./rdata:/sync
      - ./config/resilio-sync/config:/config

    restart: unless-stopped
networks:
  mynetwork:
    driver: bridge